# Generated by Django 3.1.1 on 2020-09-22 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='_customuser_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
