# Generated by Django 3.1.1 on 2020-09-22 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_scheduling', '0002_auto_20200922_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson_scheduling.subject'),
        ),
    ]
