# Generated by Django 3.1.1 on 2020-09-22 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_scheduling', '0005_auto_20200922_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='lesson_scheduling.subject'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
