# Generated by Django 3.1.1 on 2020-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_scheduling', '0006_auto_20200922_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='lesson_time',
            field=models.DateTimeField(default=True),
        ),
    ]
