# Generated by Django 3.1.1 on 2020-09-23 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_scheduling', '0007_auto_20200923_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='lesson_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 19, 35, 44, 235613)),
        ),
    ]
