# Generated by Django 3.1.1 on 2020-09-24 14:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_scheduling', '0009_auto_20200923_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='lesson_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 14, 5, 17, 496312, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_time', to='lesson_scheduling.subject'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='lesson_date', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='subject', to=settings.AUTH_USER_MODEL),
        ),
    ]
