# Generated by Django 3.1.1 on 2020-09-24 14:17

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_scheduling', '0010_auto_20200924_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='lesson_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 14, 17, 40, 779787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
