# Generated by Django 3.1.1 on 2020-09-25 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_scheduling', '0011_auto_20200924_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='lesson_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 17, 56, 44, 671856, tzinfo=utc)),
        ),
    ]
