# Generated by Django 3.1.1 on 2020-09-25 22:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_scheduling', '0012_auto_20200925_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='lesson_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 22, 10, 8, 482308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
